export const UPDATE_LOCKER_SELECTED = "UPDATE_LOCKER_SELECTED";
export const UPDATE_COST = "UPDATE_COST";
export const UPDATE_MONEY = "UPDATE_MONEY";
export const DELETE_MONEY = "DELETE_MONEY";
export const UPDATE_MODAL_SUCCESS = "UPDATE_MODAL_SUCCESS";
export const UPDATE_MODAL_UNAVAILABLE = "UPDATE_MODAL_UNAVAILABLE";
export const UPDATE_CHANGE_SUCCESS = "UPDATE_CHANGE_SUCCESS";
