export const UPDATE_LOCKER_SELECTED = "UPDATE_LOCKER_SELECTED";
export const UPDATE_COST = "UPDATE_COST";
export const UPDATE_MONEY = "UPDATE_MONEY";
export const UPDATE_CONFIRM_LOCKER = "UPDATE_CONFIRM_LOCKER";
